[versions]
# Core tool chains
agp = "9.0.0"
kotlin = "2.3.10"
ksp = "2.3.5"

# AndroidX / UI
coreKtx = "1.17.0"
splashscreen = "1.2.0"
activity = "1.12.3"
appcompat = "1.7.1"
recyclerView = "1.4.0"
androidxConstraintlayout = "2.2.1"
androidxFragment = "1.8.9"
nav_version = "2.9.7"

# Lifecycle / Startup
androidxLifecycle = "2.10.0"
androidXStartup = "1.2.0"

# Compose
compose-bom = "2026.02.00"

# Firebase
googleServices = "4.4.4"
firebase-bom = "34.9.0"
firebase-crashlytics = "3.0.6"
playServicesAuth = "21.5.0"
facebookLogin = "18.1.3"

# Material (Views)
material = "1.13.0"

# Data / DB
datastore = "1.2.0"
androidxRoom = "2.8.4"

# DI
hilt = "2.59.1"
hiltNavigation = "1.3.0"

# Net
retrofit = "3.0.0"
okhttp = "5.3.2"
gson = "2.13.2"
sandwich = "2.2.1"

# Coroutines
coroutines = "1.10.2"

# Logs / utils
timber = "5.0.1"
whatIf = "1.2.1"
bundler = "1.0.4"
progressView = "1.1.3"
transformationLayout = "1.1.6"
playCore = "2.0.2"

# Images
coil = "3.3.0"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
androidxTest = "1.7.0"
espressoCore = "3.7.0"
truth = "1.4.5"
turbine = "1.2.1"
mockitoKotlin = "6.2.3"
mockitoInline = "5.2.0"
robolectric = "4.16.1"
testRunner = "1.7.0"
androidxArchCore = "2.2.0"
baseAdapter = "1.0.4"
swiperefreshlayout = "1.2.0"
playServicesGames = "24.0.0"
uiText = "1.10.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices"}
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

# Views (si sigues usando)
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerView" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }

# Lifecycle / Startup
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidXStartup" }

# DataStore / Room
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

# DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }

# Coroutines
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Utils
whatif = { group = "com.github.skydoves", name = "whatif", version.ref = "whatIf" }
bundler = { group = "com.github.skydoves", name = "bundler", version.ref = "bundler" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
progressView = { group = "com.github.skydoves", name = "progressview", version.ref = "progressView" }
transformationLayout = { group = "com.github.skydoves", name = "transformationlayout", version.ref = "transformationLayout" }
play-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "playCore" }

# Networking
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }
okhttp-mockserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
sandwich = { group = "com.github.skydoves", name = "sandwich", version.ref = "sandwich" }

# Images
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }


# Compose BOM + artifacts
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8"}
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav_version" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

# Firebase BOM + artifacts
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ndk"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTest" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
android-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInline" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-arch-core = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCore" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# customViews
baseAdapter = { group = "com.github.skydoves", name = "baserecyclerviewadapter", version.ref = "baseAdapter" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
play-services-games = { group = "com.google.android.gms", name = "play-services-games", version.ref = "playServicesGames" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
facebook-login = { group = "com.facebook.android", name = "facebook-login", version.ref = "facebookLogin" }
